name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-frontend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-frontend:latest

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          script: |
            # remove stopped containers and dangling images
            docker container prune -f && docker image prune -f
            
            # stop and remove existing container if running
            docker rm -f portfolio-frontend || true
            
            # remove docker image
            docker rmi densoftdev/portfolio-frontend:latest
            
            # docker pull image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-frontend:latest
            
            # run docker container
            docker run --name portfolio-frontend -d -p 3000:3000 \
              -e NEXT_PUBLIC_BASE_URL="${{ secrets.NEXT_PUBLIC_BASE_URL }}" \
              -e NEXT_PUBLIC_GA_MEASUREMENT_ID="${{ secrets.NEXT_PUBLIC_GA_MEASUREMENT_ID }}" \
              ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-frontend:latest
            
            


