name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v2

      - name: Build and push Docker images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t portfolio-frontend --build-arg NEXT_PUBLIC_BASE_URL="${{secrets.NEXT_PUBLIC_BASE_URL}}" NEXT_PUBLIC_GA_MEASUREMENT_ID="{{secrets.NEXT_PUBLIC_GA_MEASUREMENT_ID}}" .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push portfolio-frontend

#      - name: SSH into EC2 and deploy with Docker Compose
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ${{ secrets.EC2_USERNAME }}
#          key: ${{ secrets.EC2_PRIVATE_KEY }}
#          script: |
#            cd /path/to/your/project
#            docker-compose pull
#            docker-compose up -d
